# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Product.proto',
  package='service',
  syntax='proto3',
  serialized_options=b'Z\010./server',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rProduct.proto\x12\x07service\" \n\x0eProductRequest\x12\x0e\n\x06ProdId\x18\x01 \x01(\x05\"$\n\x0fProductResponse\x12\x11\n\tProdStock\x18\x01 \x01(\x05\x32S\n\x0bProdService\x12\x44\n\x0fGetProductStock\x12\x17.service.ProductRequest\x1a\x18.service.ProductResponseB\nZ\x08./serverb\x06proto3'
)




_PRODUCTREQUEST = _descriptor.Descriptor(
  name='ProductRequest',
  full_name='service.ProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProdId', full_name='service.ProductRequest.ProdId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=58,
)


_PRODUCTRESPONSE = _descriptor.Descriptor(
  name='ProductResponse',
  full_name='service.ProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProdStock', full_name='service.ProductResponse.ProdStock', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['ProductRequest'] = _PRODUCTREQUEST
DESCRIPTOR.message_types_by_name['ProductResponse'] = _PRODUCTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductRequest = _reflection.GeneratedProtocolMessageType('ProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTREQUEST,
  '__module__' : 'Product_pb2'
  # @@protoc_insertion_point(class_scope:service.ProductRequest)
  })
_sym_db.RegisterMessage(ProductRequest)

ProductResponse = _reflection.GeneratedProtocolMessageType('ProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRESPONSE,
  '__module__' : 'Product_pb2'
  # @@protoc_insertion_point(class_scope:service.ProductResponse)
  })
_sym_db.RegisterMessage(ProductResponse)


DESCRIPTOR._options = None

_PRODSERVICE = _descriptor.ServiceDescriptor(
  name='ProdService',
  full_name='service.ProdService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=98,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProductStock',
    full_name='service.ProdService.GetProductStock',
    index=0,
    containing_service=None,
    input_type=_PRODUCTREQUEST,
    output_type=_PRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODSERVICE)

DESCRIPTOR.services_by_name['ProdService'] = _PRODSERVICE

# @@protoc_insertion_point(module_scope)
